name: Update blocklist daily

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ALL }}

      - name: Mkdir
        run: |
          mkdir -p temp adh/tmp adh/backup

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install HostlistCompiler
        run: npm install -g @adguard/hostlist-compiler

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libre2-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r py/requirements.txt

      - name: Download and preprocess
        run: |
          python py/preprocess.py

      - name: Commit and push changes if any
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: download and preprocess"
          file_pattern: "adh/tmp/*.txt"

      - name: Compile blocklist
        run: |
          hostlist-compiler -c adh/tmp/config0.json -o temp/blocklist.txt
          hostlist-compiler -c adh/tmp/config2.json -o adh/blocklist-merged.txt
          mv adh/blocklist-merged.txt adh/blocklist.txt
          rm -f temp/blocklist.txt

      - name: Commit and push blocklist if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update blocklist daily"
          file_pattern: "adh/blocklist.txt"

      - name: Compile domain-blocklist
        run: |
          hostlist-compiler -c adh/tmp/config1.json -o temp/domain-blocklist.txt
          hostlist-compiler -c adh/tmp/config3.json -o adh/domain-blocklist-merged.txt
          mv adh/domain-blocklist-merged.txt adh/domain-blocklist.txt
          rm -f temp/domain-blocklist.txt

      - name: Commit and push domain-blocklist if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update domain-blocklist daily"
          file_pattern: "adh/domain-blocklist.txt"

      - name: Compile ip blocklist
        run: python py/process_ip_blocklist.py

      - name: Commit and push ip blocklist if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update ip blocklist daily"
          file_pattern: "adh/backup/*.txt"
